<?php

$config["settings"] =  array (
  'aijuhe_founder' => '1',
  'auth_key' => 'VPAjQdMMQRtrQPeT',
  'charset' => 'utf-8',
  'close_second_verify_enable' => '1',
  'compiled_root_path' => './cache/templates/',
  'cookie_domain' => '',
  'cookie_expire' => '30',
  'cookie_path' => '/',
  'cookie_prefix' => 'TTtuangou_ZFn609_',
  'copyright' => '版权所有：汕头市天隆国际旅行社有限公司
联系我们：0754-86508008  QQ:619918259 公众微信：天隆国旅  新浪微博：汕头天隆国际旅行社',
  'count_online_user' => '1',
  'db_debug' => '0',
  'db_host' => 'localhost',
  'db_name' => 'tttuangou',
  'db_pass' => '',
  'db_persist' => '0',
  'db_port' => '3306',
  'db_table_prefix' => 'cenwor_',
  'db_type' => 'mysql',
  'db_user' => 'root',
  'default_module' => 'index',
  'down_app' => '1',
  'gzip' => '0',
  'icp' => ' 粤ICP备10240558号-5 ',
  'index_meta_description' => '汕头旅行社,汕头天隆国旅,天隆旅游,天隆旅行社,汕头旅游,汕头网上旅游,汕头旅游集散中心,汕头签证,汕头门票,汕头旅游特产',
  'index_meta_keywords' => '汕头旅行社,汕头旅游,汕头网上旅游',
  'language' => 'zh-CN',
  'maxthumbheight' => '600',
  'maxthumbwidth' => '800',
  'meta_description' => '汕头旅行社,天隆国旅',
  'meta_keywords' => '汕头旅行社,汕头天隆国旅,天隆旅游,天隆旅行社,汕头旅游,汕头网上旅游,汕头旅游集散中心,汕头签证,汕头门票,汕头旅游特产',
  'no_verify_email_role_id' => '1',
  'normal_default_role_id' => '3',
  'page_expire' => '0',
  'page_keyword' => '',
  'page_title' => '汕头旅行社,汕头天隆国旅,汕头旅游,汕头网上旅游,汕头旅游集散中心',
  'refresh_prevent_time' => '0',
  'refresh_times_banned_ip' => '10',
  'refresh_times_banned_ip_time' => '86400',
  'reg_email_doublee' => '0',
  'reg_email_forbid' => '',
  'reg_email_verify' => '0',
  'seccode_verify' => '0',
  'site_admin_email' => 'ydlvyou@126.com',
  'site_domain' => 'www.tl0754.com',
  'site_logo' => './images/site_logo.gif',
  'site_logo_enable' => '0',
  'site_name' => '汕头天隆国际旅行社，天隆旅游网',
  'site_notice' => '',
  'site_url' => 'http://www.tl0754.com',
  'template_path' => 'default',
  'template_root_path' => './templates/',
  'thumbheight' => 30,
  'thumbwidth' => 30,
  'timezone' => '8',
  'tongji' => '<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id=\'cnzz_stat_icon_1253037392\'%3E%3C/span%3E%3Cscript src=\'" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1253037392\' type=\'text/javascript\'%3E%3C/script%3E"));</script>',
  'tuangou_str' => '团购',
  'url_rewrite' => '',
  'watermark_position' => 0,
);
?>